# docker-compose.yaml

version: '3'
services:
  compare-app:
    build:
      context: ./app1/
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
      BACKEND_URL: http://backend:8000
  backend:
    ports:
      - "8000:8000"
    build:
      context: ./server
